name: 'Pipeline'

permissions:
  contents: read
  actions: read
  pull-requests: write
  checks: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
      branches:
        - master

env:
  APPLY_FIXES: none

jobs:

  megalinter:
    name: 'MegaLinter'
    runs-on: ubuntu-latest
    #Remover depois
    if: github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Rodando MegaLinter
        continue-on-error: true
        uses: oxsecurity/megalinter@v9
        env:
          DOCKER_IMAGE_CACHE: true
          SHOW_ELAPSED_TIME: true
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE: JAVASCRIPT,TYPESCRIPT,JSON,PRETTIER,ESLINT,JEST,PLAYWRIGHT,SPELL,COPYPASTE,HTML,CSS,MARKDOWN,YAML

      - name: Salvando relatórios do MegaLinter
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: MegaLinter reports
          include-hidden-files: "true"
          path: |
            megalinter-reports
            mega-linter.log

  unit_tests:
    needs: megalinter
    if: always()
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Instalando dependências
        run: yarn install

      - name: Executando testes unitários
        run: yarn run test

      - name: Salvando relatório unitário lcov report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: reports/coverage/lcov-report/

      - name: Salvando GitHub Test Reporter
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Relatório Unitário  
          path: reports/junit.xml 
          reporter: jest-junit
          summary-delta-report: true
          insights-report: true
          flaky-rate-report: true
          fail-rate-report: true
          slowest-report: true
          upload-artifact: true
          report-path: './ctrf/*.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mutation_tests:
    needs: megalinter
    if: github.event_name == 'workflow_dispatch'
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: 'Mutation Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Instalando dependências
        run: yarn install

      - name: Executando testes de mutação
        run: yarn run test:mutation

      - name: Salvando relatório de mutação
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutation-test-report
          path: reports/mutation/


  e2e_tests:
    needs: megalinter
    if: always()
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Instalando dependências
        run: yarn install

      - name: Instalando Browsers do Playwright
        run: yarn playwright install --with-deps

      - name: Executando testes e2e
        run: yarn run e2e

      - name: Salvando relatório E2E
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/