# Disparo Manual através de clique

# nome da pipeline
name: 'Execução Manual'

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
  workflow_dispatch:
  push:
    branches:
      - master

#tarefas dentro da pipeline = jobs

jobs:

# Unit Tests

unit_tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'yarn' 

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Executando testes unitários
        run: yarn run test

      - name: Salvando relatório unitário
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-report
          path: reports/coverage/lcov-report/

mutation_tests:
    name: 'Mutation Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'yarn'

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Executando testes de mutação
        run: yarn run test:mutation

      - name: Salvando relatório de mutação
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutation-test-report
          path: reports/mutation/


e2e_tests:
    name: 'E2E Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'yarn'

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn install

      - name: Instalando Browsers do Playwright
        run: yarn playwright install --with-deps

      - name: Executando testes e2e
        run: yarn run e2e

      - name: Salvando relatório E2E
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/